application: 3d-o-x
version: tst
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /page2
  static_files: canvas.html
  upload: /page2

- url: /tst\.json
  static_files: tst.json
  upload: /tst\.json
  
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.2"
  
- name: jinja2
  version: "2.6"
  