application: 3d-o-x
version: chtest
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /channel\.js
  static_files: channel.js
  upload: /channel\.js
  
- url: /styles\.css
  static_files: styles.css
  upload: /styles\.css
  
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.2"
  
- name: jinja2
  version: "2.6"
  