application: 3d-o-x
version: final1candidate1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /staticfiles
  static_dir: staticfiles
  
- url: /clr
  script: main.app
  login: admin
  
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.2"
  
- name: jinja2
  version: "2.6"
  