application: 3d-o-x
version: 3beta
runtime: python27
api_version: 1
threadsafe: true

handlers:
#normalise case
#At some point I am going to be tripped up by this
#doesn't work on post
- url: /[^?]*[A-Z].*
  script: case.app


- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /staticfiles
  static_dir: staticfiles
  
#- url: /
#  static_files: index.html
#  upload: index\.html
  
- url: /clr
  script: main.app
  login: admin
  
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.2"
  
- name: jinja2
  version: "2.6"
  
